"""Generate Lua constant modules for Script Extender scripting.

Turns the game indexes into ready-to-require Lua tables so SE scripts
reference `Templates["S_FTJ_GheistDaughterRing"]` instead of hardcoding
UUID strings — a typo becomes a visible nil instead of a silent failure.

Every module returns one table with bracket-quoted keys (names are not
always valid Lua identifiers).  Names that map to more than one value
are ambiguous and listed in a trailing comment instead of the table.
"""

from __future__ import annotations

from .game import Game


def _module(title: str, pairs: dict[str, str], ambiguous: set[str]) -> str:
    lines = [
        f"-- {title}",
        "-- Generated by dos2forge (`dos2forge lua`); regenerate after game patches.",
        "return {",
    ]
    for key in sorted(pairs):
        escaped_key = key.replace("\\", "\\\\").replace('"', '\\"')
        escaped_value = pairs[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  ["{escaped_key}"] = "{escaped_value}",')
    lines.append("}")
    if ambiguous:
        lines.append(f"-- omitted ({len(ambiguous)} ambiguous names):")
        for name in sorted(ambiguous):
            lines.append(f"--   {name}")
    return "\n".join(lines) + "\n"


def _uuid_map(index) -> tuple[dict[str, str], set[str]]:
    pairs: dict[str, str] = {}
    ambiguous: set[str] = set()
    for template in index.by_map_key.values():
        if not template.name:
            continue
        existing = pairs.get(template.name)
        if existing is not None and existing != template.map_key:
            ambiguous.add(template.name)
        else:
            pairs[template.name] = template.map_key
    for name in ambiguous:
        pairs.pop(name, None)
    return pairs, ambiguous


def generate_lua(game: Game) -> dict[str, str]:
    """Module file name → Lua source."""
    from .datasets import dataset

    modules: dict[str, str] = {}

    pairs, ambiguous = _uuid_map(game.templates)
    modules["Templates.lua"] = _module(
        "Root template name -> MapKey UUID", pairs, ambiguous
    )
    pairs, ambiguous = _uuid_map(game.level_instances)
    modules["Instances.lua"] = _module(
        "Level/global instance name -> MapKey UUID", pairs, ambiguous
    )
    for module_name, dataset_name, title in (
        ("Skills.lua", "skills", "Skill ids (SkillData entries)"),
        ("Statuses.lua", "statuses", "Status ids (StatusData entries)"),
    ):
        # id -> id: the value guards typos while staying the string the
        # SE API actually takes.
        ids = {record["name"]: record["name"] for record in dataset(game, dataset_name)}
        modules[module_name] = _module(title, ids, set())
    return modules
